import HeaderComp from '../../components/PageComponents/HeaderComp'
import 'tailwindcss/tailwind.css'
import './globals.css'
import { Inter } from 'next/font/google'
import { CartProvider } from '@/context/cart'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          {children}
        </CartProvider>
        
      </body>
    </html>
  )
}
